import { Footer } from '@/components/common/Footer'
import { Header } from '@/components/common/Header'
import { Toaster } from '@/components/ui/sonner'
import { createClient } from '@/lib/supabaseServerClient'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const supabase = await createClient()
	const {
		data: { session }
	} = await supabase.auth.getSession()

	return (
		<html lang='ja'>
			<body
				className={cn(
					geistSans.variable,
					geistMono.variable,
					'antialiased',
					'min-h-dvh'
				)}
			>
				<Header session={session} />
				<main>{children}</main>
				<Toaster position='top-right' closeButton={true} />
				<Footer />
			</body>
		</html>
	)
}
